services:
  - type: web
    name: telegram-miniapp-bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn bot:application"
    plan: free
    region: frankfurt
